-- MySQL Script generated by MySQL Workbench
-- Thu 07 Apr 2022 14:54:02 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Vapor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Vapor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Vapor` DEFAULT CHARACTER SET utf8 ;
USE `DB_Vapor` ;

-- -----------------------------------------------------
-- Table `DB_Vapor`.`account_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`account_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`account_tbl` (
  `idaccount_tbl` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `isBanned` TINYINT(1) NOT NULL,
  `biography` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idaccount_tbl`),
  UNIQUE(`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Vapor`.`game_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`game_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`game_tbl` (
  `idgame_tbl` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `isDisabled` TINYINT NOT NULL,
  PRIMARY KEY (`idgame_tbl`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Vapor`.`Achievement_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`Achievement_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`Achievement_tbl` (
  `idAchievment_tbl` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `game_tbl_idgame_tbl` INT NOT NULL,
  PRIMARY KEY (`idAchievment_tbl`),
  INDEX `fk_Achievment_tbl_game_tbl_idx` (`game_tbl_idgame_tbl` ASC) VISIBLE,
  CONSTRAINT `fk_Achievment_tbl_game_tbl`
    FOREIGN KEY (`game_tbl_idgame_tbl`)
    REFERENCES `DB_Vapor`.`game_tbl` (`idgame_tbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Vapor`.`achievementsPerAccount_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`achievementsPerAccount_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`achievementsPerAccount_tbl` (
  `account_tbl_idaccount_tbl` INT NOT NULL,
  `Achievment_tbl_idAchievment_tbl` INT NOT NULL,
  PRIMARY KEY (`account_tbl_idaccount_tbl`, `Achievment_tbl_idAchievment_tbl`),
  INDEX `fk_account_tbl_has_Achievment_tbl_Achievment_tbl1_idx` (`Achievment_tbl_idAchievment_tbl` ASC) VISIBLE,
  INDEX `fk_account_tbl_has_Achievment_tbl_account_tbl1_idx` (`account_tbl_idaccount_tbl` ASC) VISIBLE,
  CONSTRAINT `fk_account_tbl_has_Achievment_tbl_account_tbl1`
    FOREIGN KEY (`account_tbl_idaccount_tbl`)
    REFERENCES `DB_Vapor`.`account_tbl` (`idaccount_tbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_tbl_has_Achievment_tbl_Achievment_tbl1`
    FOREIGN KEY (`Achievment_tbl_idAchievment_tbl`)
    REFERENCES `DB_Vapor`.`Achievement_tbl` (`idAchievment_tbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Vapor`.`gamesPerAccount_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`gamesPerAccount_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`gamesPerAccount_tbl` (
  `account_tbl_idaccount_tbl` INT NOT NULL,
  `game_tbl_idgame_tbl` INT NOT NULL,
  PRIMARY KEY (`account_tbl_idaccount_tbl`, `game_tbl_idgame_tbl`),
  INDEX `fk_account_tbl_has_game_tbl_game_tbl1_idx` (`game_tbl_idgame_tbl` ASC) VISIBLE,
  INDEX `fk_account_tbl_has_game_tbl_account_tbl1_idx` (`account_tbl_idaccount_tbl` ASC) VISIBLE,
  CONSTRAINT `fk_account_tbl_has_game_tbl_account_tbl1`
    FOREIGN KEY (`account_tbl_idaccount_tbl`)
    REFERENCES `DB_Vapor`.`account_tbl` (`idaccount_tbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_tbl_has_game_tbl_game_tbl1`
    FOREIGN KEY (`game_tbl_idgame_tbl`)
    REFERENCES `DB_Vapor`.`game_tbl` (`idgame_tbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
