-- MySQL Script generated by MySQL Workbench
-- Thu 07 Apr 2022 14:54:02 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Vapor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Vapor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Vapor` DEFAULT CHARACTER SET utf8 ;
USE `DB_Vapor` ;

-- -----------------------------------------------------
-- Table `DB_Vapor`.`account_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`account_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`account_tbl` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `isBanned` TINYINT(1) NOT NULL,
  `biography` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE(`username`));



-- -----------------------------------------------------
-- Table `DB_Vapor`.`game_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`game_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`game_tbl` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `isDisabled` TINYINT NOT NULL,
  `downloadLInk` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`));



-- -----------------------------------------------------
-- Table `DB_Vapor`.`achievement_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`achievement_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`achievement_tbl` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `game_Id` INT NOT NULL,
  `isDisabled` TINYINT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `game_achievement_Id_Idx` (`game_Id` ASC) VISIBLE,
  CONSTRAINT `game_achievement_Id_Idx`
    FOREIGN KEY (`game_Id`)
    REFERENCES `DB_Vapor`.`game_tbl` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `DB_Vapor`.`achievementsPerAccount_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`achievementsPerAccount_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`achievementsPerAccount_tbl` (
  `account_Id` INT NOT NULL,
  `achievement_Id` INT NOT NULL,
  PRIMARY KEY (`account_Id`, `achievement_Id`),
  INDEX `achievement_Id_Idx` (`achievement_Id` ASC) VISIBLE,
  INDEX `account_achievement_Id_Idx` (`account_Id` ASC) VISIBLE,
  CONSTRAINT `account_achievement_Id_Idx`
    FOREIGN KEY (`account_Id`)
    REFERENCES `DB_Vapor`.`account_tbl` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `achievement_Id_Idx`
    FOREIGN KEY (`achievement_Id`)
    REFERENCES `DB_Vapor`.`achievement_tbl` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `DB_Vapor`.`gamesPerAccount_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Vapor`.`gamesPerAccount_tbl` ;

CREATE TABLE IF NOT EXISTS `DB_Vapor`.`gamesPerAccount_tbl` (
  `account_Id` INT NOT NULL,
  `game_Id` INT NOT NULL,
  PRIMARY KEY (`account_Id`, `game_Id`),
  INDEX `game_game_Id_Idx` (`game_Id` ASC) VISIBLE,
  INDEX `account_game_Id_Idx` (`account_Id` ASC) VISIBLE,
  CONSTRAINT `account_game_Id_Idx`
    FOREIGN KEY (`account_Id`)
    REFERENCES `DB_Vapor`.`account_tbl` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game_game_Id_Idx`
    FOREIGN KEY (`game_Id`)
    REFERENCES `DB_Vapor`.`game_tbl` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
